<?php
define("SUCCESS",1);
define("ERR_SERVER_ERROR",-1);
define("ERR_NO_RESULT",-2);
define("SUCCESS_BUT_SENSOR_NOT_EXIST",-3);
define("SUCCESS_BUT_SENSORDATATYPE_NOT_EXIST",-4);
define("DATA_NOT_EXIST",-5);
define("LADDR_NOT_EXIST",-6);
define("TYPE_NOT_EXIST",-7);
define("SENSOR_NOT_EXIST",-8);
define("REGISTED",-9);
define("LOGINFAIL",-10);
define("SERVER_BUSY",-11);
define("MAIL_FAIL",-14);

define("OUTERR_SENSOR_NOT_EXIST",-101);
define("OUTERR_SENSORDATATYPE_NOT_EXIST",-102);
define("OUTERR_NO_SENSOR",-103);
define("OUTERR_SENSOR_EXSIT",-104);
define("OUTERR_NO_RESULT",-105);
define("OUTERR_SERVER_ERROR",-106);
?>